[versions]
graalvm-native = "1.1.14"
spring-boot = "4.1.1"
springdoc = "3.1.1"
swagger = "2.2.54"
assertj = "3.27.7"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations"}
swagger-annotations = { module = "io.swagger.core.v3:swagger-annotations-jakarta", version.ref = "swagger" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
